### ISSUE TITLE
Error: invalid key

### ISSUE THREAD

**Issue by manuel-uberti** [ocharles/papers#10]
Hi, 

first of all thanks for this useful collection of papers.

I followed the instructions on the README, but when I try to set `remote.upstream.annex-sync` I get this error:

```
❯ git config remote.upstream.annex-sync=false
error: invalid key: remote.upstream.annex-sync=false
```

I am no `git-annex` expert, so I was wondering: is there another option I need to set?

These are some details about my system, in case they are needed:
```
~/githubs/papers master 
❯ git --version
git version 2.17.1

~/githubs/papers master 
❯ git-annex version
git-annex version: 6.20180227
```

Thank you.

**Comment by ocharles** [comment]
I see you closed this. Did you manage to fix it?

**Comment by manuel-uberti** [comment]
Actually no, sorry, I thought you missed this because you were busy on something else.

**Comment by ocharles** [comment]
Busy but it doesn't make it any less important :) Let's keep it open, I'll get to it when I get a chance.

**Comment by kyleam** [comment]
Hi @manuel-uberti, you can fix this by `s/=/ /` and `s/upstream/origin/` (see gh-11).

**Comment by kyleam** [comment]
> Although when I do git annex sync origin I get:
> ...
> But yes, I can't push the original repo of course.

Right, that's expected.  Here's `man git-annex`s entry for that config variable:

```
remote.<name>.annex-sync
       If set to false, prevents git-annex sync (and the git-annex assistant) from sync‐
       ing with this remote by default. However, git annex sync <name> can still be used
       to sync with the remote.
```

So, you won't run into issues if you just `git annex sync`, but you also won't getting any updates from `origin`.  In this scenario, you can use standard `git fetch origin/git merge master` along with `git annex merge`.  Or, to make `git annex sync` work, you can use `remote.origin.annex-readonly` instead of `remote.origin.annex-sync`.  I'll add that to gh-11.

**Comment by manuel-uberti** [comment]
Awesome, now everything works. Thanks again, @kyleam.
